import { Schema, model } from "mongoose";

const Produtos = new Schema({
  produto: {
    modelo: String,
    marca: String,
    descricao: String,
    promocao: Boolean,
    promocao2: Boolean,
    qtdpromocao2: Number,
    precomaior: String,
    preco: String,
    desconto: String,
    categoria: String,
    subcategoria1: String,
    subcategoria2: String,
    subcategoria3: String,
    subcategoria4: String,
    cor: {
      cor1: String,
      t1: { tamanho1: String, quantidade1: String },
      t2: { tamanho2: String, quantidade2: String },
      t3: { tamanho3: String, quantidade3: String },
      t4: { tamanho4: String, quantidade4: String },
      foto1: String,
      foto2: String,
      foto3: String,
      foto4: String,
    },
    cor: {
      cor2: String,
      t5: { tamanho5: String, quantidade5: String },
      t6: { tamanho6: String, quantidade6: String },
      t7: { tamanho7: String, quantidade7: String },
      t8: { tamanho8: String, quantidade8: String },
      foto5: String,
      foto6: String,
      foto7: String,
      foto8: String,
    },
    cor: {
      cor3: String,
      t9: { tamanho9: String, quantidade9: String },
      t10: { tamanho10: String, quantidade10: String },
      t11: { tamanho11: String, quantidade11: String },
      t12: { tamanho12: String, quantidade12: String },
      foto9: String,
      foto10: String,
      foto11: String,
      foto12: String,
    },
    cor: {
      cor4: String,
      t13: { tamanho13: String, quantidade13: String },
      t14: { tamanho14: String, quantidade14: String },
      t15: { tamanho15: String, quantidade15: String },
      t16: { tamanho16: String, quantidade16: String },
      foto13: String,
      foto14: String,
      foto15: String,
      foto16: String,
    },
    cor: {
      cor5: String,
      t17: { tamanho17: String, quantidade17: String },
      t18: { tamanho18: String, quantidade18: String },
      t19: { tamanho19: String, quantidade19: String },
      t20: { tamanho20: String, quantidade20: String },
      foto17: String,
      foto18: String,
      foto19: String,
      foto20: String,
    },
    cor: {
      cor6: String,
      t21: { tamanho21: String, quantidade21: String },
      t22: { tamanho22: String, quantidade22: String },
      t23: { tamanho23: String, quantidade23: String },
      t24: { tamanho24: String, quantidade24: String },
      foto21: String,
      foto22: String,
      foto23: String,
      foto24: String,
    }

  }
})

export default model("Produtos", Produtos);
